#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_APP_ASSERT_PRESENT
#define SL_CATALOG_BLUETOOTH_PRESENT
#define SL_CATALOG_GATT_CONFIGURATION_PRESENT
#define SL_CATALOG_MPU_PRESENT
#define SL_CATALOG_MX25_FLASH_SHUTDOWN_PRESENT
#define SL_CATALOG_POWER_MANAGER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
